### PR TITLE
Allow custom react components to be passed in

### PR DESCRIPTION
**Pull request by jjt**
Allows passing in custom react components to replace the standard `<p>`, `<li>`, `<a>`, etc.

### CODE REVIEW

**Comment by tmcw** [comment]
Huh - what's the use case for this?

**Comment by jjt** [comment]
[This React-based slidedeck](https://github.com/FormidableLabs/spectacle) defines components with inline styles for each element. So we need to output `<Text>` instead of `<p>`, `<Link>` instead of `<a>`, etc.

**Comment by tmcw** [comment]
Gotcha. Can you add documentation in the [options part of README.md](https://github.com/mapbox/mdast-react#configuration)?

**Comment by jjt** [comment]
Sure thing

**Comment by wooorm** [comment]
@tmcw just saw that the mdastrc congifuration still shows 'html' instead of 'react'!

**Comment by jjt** [comment]
I take no credit/blame for that one ;)

**Comment by jjt** [comment]
@tmcw anything more I can do to push this along?

**Comment by tmcw** [comment]
:+1: merged, going to do another pass on the readme and then push a release.

**Comment by jjt** [comment]
Great, thx!

**Pull request closed without merging**
