### PR TITLE
Support footnote definitions in output

### PR DESCRIPTION
**Pull request by ciaranw**
This patch adds the footnote defintions to the output of this plugin. As part of this, I added the node's `attributes` to the props for each react component, so you can specify className, id etc.

### CODE REVIEW

**Comment by tmcw** [comment]
The footnotes addition looks great, but I don't feel comfortable including all of the node attributes because it [introduces the possibility of a DOM Clobbering attack](http://www.thespanner.co.uk/2013/05/16/dom-clobbering/) if we allow uncontrolled ids and name attributes.

**Comment by ciaranw** [comment]
Would you be happy with a whitelist approach to this? To get the footnotes working we just need to include `id` and `class`/`className`, so just those to start?

**Comment by tmcw** [comment]
The class attribute is fine, but id & name are the ones that open the attack vector.

**Comment by ciaranw** [comment]
Hmm, we need to give each footnote definition node an id, otherwise you can't link to them. Have you got a suggested workaround for this?

**Comment by tmcw** [comment]
Are the footnote IDs automatically generated? It looks so in this example, like they'd be `fn-1` and so on. In that case that'd be fine.

**Comment by ciaranw** [comment]
Yes, the footnote ids are generated, however you can specify named footnotes like [^test]. So for that footnote, it would have an id of `fn-test`.

**Comment by wooorm** [comment]
@ciaranw you could probably omit that behaviour when compiling though, it’s not essential for functioning but nice slug-sugar and easy to use as an author.

**Comment by ciaranw** [comment]
Ok, i've made a couple of changes which allow footnote ids through since they are generated. Otherwise, add all of the nodes attributes to props apart from `id` and `name`.

**Comment by tmcw** [comment]
Should this show a footnotes section at the end of the output? Trying this out in our demo shows the footnote properly becoming superscript, but not linked to anything.

**Comment by ciaranw** [comment]
It should show the footnotes after all the regular content. There is a test [here](https://github.com/ciaranw/mdast-react/blob/00a033a4abdbcbf3b1b66f321691b676c45a1da7/test/fixtures/footnotes/output.html) which shows the current behaviour.

**Comment by ciaranw** [comment]
You could be missing the footnotes because your footnote definition is being parsed as a regular definition. The regular definition parser's regex is before the footnote definition regex, and will match unless your footnote definition has at least one space in it:

`[^1]: footnote` gets parsed as a definition
`[^1]: footnote definition` gets parsed as a footnote definition

I'd love for this to be merged in to master, since we'd like to use footnotes in markdown on our project, so if there's anything outstanding let me know and I'll get right on to it.

**Comment by tmcw** [comment]
Yep, I was not defining footnotes properly.

**Pull request merged**
