### PR TITLE
Update for remark@7.0.0

### PR DESCRIPTION
**Pull request by wooorm**
Hi! 👋 

remark 7.0.0 was recently released, which packs some changes. More about those can be found [here](https://github.com/wooorm/remark/releases/tag/7.0.0). I’ve updated this repo accordingly.

This packs some changes to list rendering, which are now much better, as can be seen in the changed for the `list` fixture in this PR.

I couldn’t help myself from also refactoring a bit (err, quite a bit, maybe?). I opted for xo as that packs less config files. Anyway, I’m happy to change that to something else, or drop the refactoring!

### CODE REVIEW

**Comment by wooorm** [comment]
Edit: this now also comes with a fix for GH-28!

**Comment by KyleAMathews** [comment]
@wooorm nice!

**Review by tmcw — APPROVED** [review]
Excellent, thanks!

**Comment by wooorm** [comment]
🎉

**Comment by tmcw** [comment]
👍 Cool, rolling a new release. I think for my personal projects I'm going to do a system-wide shift to [prettier](https://github.com/prettier/prettier), finally the first thing to mirror gofmt's right-feeling approach. But this repo still sits under Mapbox ownership, so 🤷‍♂️

**Comment by wooorm** [comment]
I’m good with all the major styles with (almost) no config: standard, prettier, or xo, so I’m fine with switching!

**Pull request merged**
